.gitignore, README.md, setup.py, test/dsdl/test_common.py, test/dsdl/test_parser.py, test/dsdl/test_signature.py, test/test_driver.py, test/test_node.py, test/test_transport.py, uavcan/__init__.py, uavcan/driver.py, uavcan/dsdl/__init__.py, uavcan/dsdl/common.py, uavcan/dsdl/parser.py, uavcan/dsdl/signature.py, uavcan/dsdl/type_limits.py, uavcan/monitors/__init__.py, uavcan/node.py, uavcan/services/__init__.py, uavcan/transport.py
This is still a work-in-progress.
@bendyer I'd like to ask a few questions concerning your implementation before I continue.
* [`_instantiate()` method](https://github.com/UAVCAN/pyuavcan/blob/master/uavcan/__init__.py#L93-L99). It is initialized in `load_dsdl()`, but it is not called from anywhere. Why do we need it?
* Field initialization via the constructor of `CompoundValue` seems to be intended, but not implemented. Is my understanding correct that the proper way of adding this feature would be adding necessary `setattr()` calls [here](https://github.com/UAVCAN/pyuavcan/blob/master/uavcan/transport.py#L376)? E.g.:
```python
for name, value in kwargs.items():
setattr(self, name, value)
```
* The logic for handling incoming messages/requests/responses seems overengineered. I'm talking …
=> Global refactoring

uavcan/driver.py
This parser is much faster. It prevents data loss even on a fully congested bus at 1Mbps.
=> Slcan speed optimization

uavcan/transport.py
When running current Pyuavcan on a beaglebone black I got the following error:
```
======================================================================
FAIL: test_basic (test.test_transport.TestFloats)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test/test_transport.py", line 642, in test_basic
a.value = float('-inf')
File "uavcan/transport.py", line 296, in value
int_value = f16_from_f32(new_value)
File "uavcan/transport.py", line 172, in f16_from_f32
inval.u = inval.u ^ sign
File "uavcan/transport.py", line 153, in u
assert isinstance(value, int)
AssertionError
```
after a bit of debugging it appears to be related to how Python2 handles integers (the problem is not present in python3). This PR fixes the issues and all …
=> Fix a bug on 32bit Python 2

uavcan/__init__.py
As discussed on gitter. patch adds all folders found in ~/uavcan_custom_types to the list
of known Datatypes on loading the Module
A dialog in the Gui tool could easily symlink the folder containing the a Users datatypes to the uavcan_custom_types folder.
=> Default folder to define/symlink custom uavcan types

uavcan/app/dynamic_node_id.py, uavcan/app/file_server.py
Explicitly convert byte arrays to `bytearray` type to allow item iteration in python 2.7.
=> Python 2.7 compatabilty for byte arrays

uavcan/driver/slcan.py
As requested by @pavel-kirienko in https://github.com/ArduPilot/ardupilot/issues/8166#issuecomment-389222002, this patch increases the slcan driver receive buffer to one million in non-Mac OS.
As explained in that issue, the buffer is too small when the bus has a high number of messages.
**This was only tested in Ubuntu 16.04**
=> slcan driver: increase receive buffer size in non-Mac OS

uavcan/transport.py
Python 3.7 / PEP479 
This just catches StopIteration in `transport.py` and seems to be all that is necessary for Python 3.7 support.
=> Python 3.7 compatibility

uavcan/driver/slcan.py
The `slcan` driver can misbehave when `close()` is called more than once on a node.  This is a problem, because `close()` is called in the `SLCAN` destructor, even if it was already called by a context manager.
I tested with the following script:
```
import uavcan
for i in range(25):
node = uavcan.make_node('/dev/cu.usbmodem14431', node_id=3)
node.close()
```
And see the following error message once the GC starts reclaiming older nodes:
```
Exception ignored in: <function SLCAN.__del__ at 0x1039841e0>
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/uavcan/driver/slcan.py", line 712, in __del__
self.close()
File "/usr/local/lib/python3.7/site-packages/uavcan/driver/slcan.py", line 688, in close
if self._proc.is_alive():
File …
```
=> Don't call close more than once in slcan driver

test/test_transport.py, uavcan/dsdl/parser.py
I'm not really a python developer, hope i managed to not mess up these small changes to bad.
- For the API part I assume that the correct thing to do was to add a version field to `CompondType`. My assumption is mainly based on `CompoundType` also containing the `default_dtid`, I've not done much research how the parser is actually used except for the `test.py` script in the dsdl repo.
- I dont like the `_full_typename_version_and_dtid_from_filename` method name. Fortunately it's a private method, but perhaps `parse_filename` or something in that direction would be better?
- I've verified that if two versions of the same message exists the list returned by `parse_namespace` will have two element with the same name. When they are printed they are indistinguishable, is that a problem?
=> Also parse .uavcan files with explicit version number

.travis.yml, test/test_node.py, uavcan/node.py
This commit fixes issue #45, by adding a flag to the spin method. It
allows the user to catch exceptions thrown from messages handler. This
is useful during debugging, so that thrown exceptions can be caught by
debuggers.
Not yet tested on a real project as I don't have hardware with me. Will report testing result ASAP.
=> Re-raise callback exceptions if asked to

uavcan/transport.py
__long__ was removed in Python 3 because all __int__ are of infinite precision.
@pavel-kirienko Your review please?
[flake8](http://flake8.pycqa.org) testing of https://github.com/UAVCAN/pyuavcan on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./uavcan/transport.py:172:60: F821 undefined name 'long'
assert isinstance(value, int) or isinstance(value, long)
^
1     F821 undefined name 'long'
1
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in …
=> Define long in Python 3

.travis.yml
Python 3.3 was end of life years ago and 3.4 end of life is in less than 60 days... https://devguide.python.org/#branchstatus
Also, [Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
=> Travis CI: Drop Python 3.3 and add Python 3.6 and 3.7

.gitignore, appveyor.yml, test/dsdl/__init__.py, test/dsdl/fake_dsdl/ns0_base/ns0/20000.Type0.uavcan, test/dsdl/fake_dsdl/ns0_duplicated/ns0/20000.Type0.uavcan, test/dsdl/fake_dsdl/ns0_redefined/ns0/20000.Type0.uavcan, test/dsdl/test_load_dsdl.py, uavcan/dsdl/parser.py
duplicate == the same thing more than once. This is okay.
redefined == the same identifer used by incompatible definitions.
this is not okay.
In complex build systems duplicate dsdl files can get pulled in from
multiple dependencies and end up in long lists of paths that are
passed into the pyuavcan dsdl compiler. This change to the dsdl
parser allows this without throwing errors but enforces that the
duplicated definitions are compatible. This elminiates the need
for special case handling in build systems to try to find the duplicates
before invoking pyuavcan and adds a new check where such complex
systems will be notified when duplicated definitions get out of
sync.
=> Allowing duplicate definitions when parsing dsdl

uavcan/driver/__init__.py, uavcan/driver/python_can.py
- Fixes the issue of not having python-can installed causing an error, even though users may want to use, e.g., SocketCAN instead.
- Allows passing CAN interface configuration information using the constructor instead of requiring the use of an INI file.
- Corrects other minor issues.
=> Improve python-can driver

uavcan/transport.py
Minor change to get rid of a deprecation warning in 3.7
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
Ref: https://docs.python.org/3/whatsnew/3.7.html#id3
=> Fix Collections Deprecation Warning

test/dsdl/test_parser.py, uavcan/dsdl/parser.py
=> Check dependencies for duplicated types.

requirements.txt, setup.cfg
Since https://github.com/UAVCAN/pyuavcan/issues/103 is solved by https://github.com/UAVCAN/pydsdl/pull/39, ```pydsdl``` as requirement can be locked to ```1.4```.
Dependency nunavut also requires pydsdl 1.4, this PR solves the conflict.
This PR also fixes tests in pytest 5.4, closes https://github.com/UAVCAN/pyuavcan/issues/95
=> Update pydsdl as requirement to 1.4

uavcan/transport.py
Dynamic array lengths are encoded as any other scalar, so when they're decoded/encoded we should
make sure they're read/written as little endian scalars. This change fixes the fact that converting binary
strings to/from ints assumes the string is in big endian representation, so arrays with max length over 256 would be incorrectly encoded.
=> [legacy-v0] transport.py: Fix endianness of dynamic array lengths

pyuavcan/transport/can/media/socketcan/_socketcan.py
Closes #183 
Currently, as per Python exception chaining, the OSError is still thrown, but display of the MediaConfigurationError takes precedence.
=> socketcan: improve incorrect config error message

pycyphal/application/_transport_factory.py
"regsiters" changed to "registers" in docstring.
Instead of messed pull request https://github.com/OpenCyphal/pycyphal/pull/331
=> typo fix in _transport_factory.py docstring
